extends Node
var ListaQDim0=[ListaQ1Dim0,ListaQ2Dim0,ListaQ3Dim0,ListaQ4Dim0]
var ListaQ1Dim0=["Which of the following is a primary color?"]
var ListaQ2Dim0=["Which of the following in NOT a prime number?"]
var ListaQ3Dim0=["In which year was Dell founded?"]
var ListaQ4Dim0=["What is the meaning of life, the universe, and everything?"]

var ListaA1Dim0=["Yellow","Orange","Pink","Black"]
var ListaA2Dim0=["39","47","13","2"]
var ListaA3Dim0=["1984","1987","1996","1970"]
var ListaA4Dim0=["42","3","7","12"]
var ListaADim0=[ListaA1Dim0,ListaA2Dim0,ListaA3Dim0,ListaA4Dim0]


var ListaQ1Dim1=["How does a team move from level 1 to level 2?"]
var ListaQ2Dim1=["Lean Experiments are useful inputs at what Vision maturity level?"]
var ListaQ3Dim1=["What is the key expected outcome of Vision Level 3?"]
var ListaQ4Dim1=["Creating an outcome based roadmap is considered a good next step in which Vision maturity level?"]
var ListaQ5Dim1=[" Which of these inputs is suggested at maturity level 3 and 4?"]
var ListaQ6Dim1=[" Which of these actions is necessary to improve the maturity level from 1 to 2?"]
var ListaQ7Dim1=[" Which of these actions is necessary to improve the maturity level from 3 to 4?"]
var ListaQ8Dim1=[" What is the first thing that you need to do when your team doesn't have the product vision?"]
var ListaQ9Dim1=["Reviewing outcome based roadmap periodically with stakeholders is considered a good next step in which Vision maturity level?"]
var ListaQDim1=[ListaQ1Dim1,ListaQ2Dim1,ListaQ3Dim1,ListaQ4Dim1,ListaQ5Dim1,ListaQ6Dim1,ListaQ7Dim1,ListaQ8Dim1,ListaQ9Dim1]

var ListaA1Dim1=["By becoming aware of the Product Vision they are working on and understanding how it reflects on the goal of their development efforts.","By starting to hold Product Vision workshops.","By requiring Product Vision rationale for all items in the Product Backlog.","By using Product Vision to shape Product Decisions."]
var ListaA2Dim1=["4","1","2","3"]
var ListaA3Dim1=["The Growth Board","The Roadmap","The Metrics Board","Project Timeline"]
var ListaA4Dim1=["2","1","3","4"]
var ListaA5Dim1=[" Lean Experiments"," Product Charter Template.","OGSM.","Stakeholders Alignment."]
var ListaA6Dim1=[" Conduct detailed user research to identify personas and their problems.","Review outcome based roadmap periodically with stakeholders.","Provide PLMs with Risks and Challenges along with lean experiments information.","Continuously leverage Product Line growth board sessions to share results based on validated learning."]
var ListaA7Dim1=["Provide PLMs(Product Lifecycle Management) with Risks and Challenges along with lean experiments information.","Conduct detailed user research to identify personas and their problems."," Ensure the team establishes a routine to socialize the Product Vision (to facilitate ramp up of new members).","Continuously leverage Product Line growth board sessions to share results based on validated learning."]
var ListaA8Dim1=["Setup a Brainstorm Session with the team to create a Product Team Vision.","Create an outcome based roadmap which is in line with OGSM and customer needs.","Continuously leverage Product Line growth board sessions to share results based on validated learning"," Review outcome based roadmap periodically with stakeholders"]
var ListaA9Dim1=["Level 3","Level 1","Level 2","Level 4"]
var ListaADim1=[ListaA1Dim1,ListaA2Dim1,ListaA3Dim1,ListaA4Dim1,ListaA5Dim1,ListaA6Dim1,ListaA7Dim1,ListaA8Dim1,ListaA9Dim1]

var ListaQDim2=["What is the one expected outcome present in all Roadmap maturity levels?","At what maturity level is the Team expected to be proactively considering the needs of the users to drive roadmap decisions?","What is the best way to define maturity level 2?","The existing version of the Roadmap is a useful input for all Roadmap maturity levels, except:"]
var ListaA1Dim2=["Outcome Based Roadmap","Data Driven Roadmap","Updated Backlog","OGSM"]
var ListaA2Dim2=["4","1","2","3"]
var ListaA3Dim2=["Team has a testable outcome-based Product Roadmap through user and stakeholder input.","Team is able to adjust Roadmap based on management decisions.","Team only accepts items funded by leadership in their Roadmap.","Team reviews Product Roadmap every quarter."]
var ListaA4Dim2=["1","2","3","4"]
var ListaADim2=[ListaA1Dim2,ListaA2Dim2,ListaA3Dim2,ListaA4Dim2]
